meanings = {"H_URBRURAL":"Urban-Rural Settlement type",
"Q3" :"Importance in life: Leisure time",
"Q1":"Importance in life: Family",
"Q5":"Importance in life: Work",
"Q18" : "Neighbors: Drug addicts",
"Q19" : "Neighbors: People of a different race",
"Q20" : "Neighbors: People who have AIDS",
"Q21" : "Neighbors: Immigrants/foreign workers",
"Q22" : "Neighbors: Homosexuals",
"Q23" : "Neighbors: People of a different religion",
"Q24" : "Neighbors: Heavy drinkers",
"Q33" : "Jobs scarce: Men should have more right to a job than women",
"Q47" : "State of health (subjective)",
"Q58" : "How much you trust: Your family",
"Q67" : "Confidence: Television",
"Q69" : "Confidence: The Police",
"Q108": "Government ́s vs individual ́s responsibility",
"Q109": "Competition good or harmful",
"Q138": "Frequency in your neighborhood: Sexual harassment",
"Q161": "One of the bad effects of science is that it breaks down people's ideas of right and wrong",
"Q172": "Apart from weddings and funerals, about how often do you pray?",
"Q206": "Information source: Internet",
"Q213": "Social activism: Donating to a group or campaign",
"Q238": "Political system: Having a democratic political system",
"Q252": "Satisfaction with the political system performance",
"Q260": "Sex",
"Q262": "age",
"Q262sq": "age squared",
"Q263" : "Respondent immigrant",
"Q271" : "Do you live with your parents",
"Q273" : "Marital status",
"Q274" : "number of kids",
"Q275R": "Highest educational level: Respondent (recoded into 4 groups)",
"Q279" : "Employment status",
"Q288" : "Scale of incomes",
"Q185" : "Justifiable: Divorce",
"Q186" : "Justifiable: Sex before marriage"}